# Project name
name: 'edp_data_domain'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

vars:
  'full_load_warehouse': " {%- if env_var('DBT_ENVIRONMENT')|lower == 'team_dev' -%}dev {%- else -%} {{ env_var('DBT_ENVIRONMENT') | lower }} {%- endif -%}_l_wh"
  'initial_load_warehouse': " {%- if env_var('DBT_ENVIRONMENT')|lower == 'team_dev' -%}dev {%- else -%} {{ env_var('DBT_ENVIRONMENT') | lower }} {%- endif -%}_m_wh"
  'incremental_load_warehouse': " {%- if env_var('DBT_ENVIRONMENT')|lower == 'team_dev' -%}dev {%- else -%} {{ env_var('DBT_ENVIRONMENT') | lower }} {%- endif -%}_s_wh"

  'set_full_refresh': 'false'
  'dbt_date:time_zone': 'America/Boise'
  'incremental_load_unit': 'hh' # unit of time to use in incremental load. can be any of the supported Snowflake date/time parts (see docs for the dateadd function)
  'incremental_load_offset': '-24' # number of date part units specified in incremental_load_unit to overlap incremental load to allow for late arriving or out of sequence records
  'staging_data_source': 'enterprise_data_platorm' # dbt project containing source data for integration, curation, and consumption layers
  'legacy_source_system': 'legacy_facets'
  'gemstone_source_system': 'gemstone_facets'
  'HCDM_tenant_id': 'BCI'
  'HCDM_legacy_source_system': 'FACETS_LGC'
  'HCDM_gemstone_source_system': 'FACETS_GMS'
  'valenz_source_system': 'VALENZ'
  'melissa_source_system': 'MELISSA_DATA'
  'mdm_source_system': 'MDM'

  'consumption_database_name': " {%- if env_var('DBT_ENVIRONMENT')|lower == 'team_dev' -%}dev_con_db {%- elif env_var('DBT_ENVIRONMENT')|lower == 'dev' -%} {{ target.database }} {%- else -%} {{ env_var('DBT_ENVIRONMENT') | lower }}_con_db {%- endif -%}"
  'extract_schema': 'extract_elig'
  'consumption_deploy_frl': " {%- if env_var('DBT_ENVIRONMENT')|lower == 'team_dev' -%}dev_con_deploy_frl {%- elif env_var('DBT_ENVIRONMENT')|lower == 'dev' -%}dev_con_deploy_frl {%- else -%} {{ env_var('DBT_ENVIRONMENT') | lower }}_con_deploy_frl {%- endif -%}"
  'common_database_name': " {%- if env_var('DBT_ENVIRONMENT')|lower == 'team_dev' -%}dev_common_db {%- elif env_var('DBT_ENVIRONMENT')|lower == 'dev' -%} {{ target.database }} {%- else -%} {{ env_var('DBT_ENVIRONMENT') | lower }}_common_db {%- endif -%}"
  'config_schema': 'con_config'
  'common_deploy_frl': " {%- if env_var('DBT_ENVIRONMENT')|lower == 'team_dev' -%}dev_common_deploy_frl {%- elif env_var('DBT_ENVIRONMENT')|lower == 'dev' -%}dev_common_deploy_frl {%- else -%} {{ env_var('DBT_ENVIRONMENT') | lower }}_common_deploy_frl {%- endif -%}"

on-run-end:
  - "{{ dbt_artifacts.upload_results(results) }}"


models:
  dbt_artifacts:
    +database: "common_db"
    +schema: "int_logs"
  edp_data_domain:

    common:
      +database: "common_db"
      integration_logs:
        +schema: "int_logs"
      con_config:
        +schema: "con_config"

    integration:
      +enabled: true
      +database: "int_db"
      +materialized: "incremental"
      +incremental_strategy: "merge"
      +on_schema_change: "fail"

      cust_svc:
        +schema: "cust_svc"
        +materialized: "incremental"
        +incremental_strategy: "merge"
        +on_schema_change: "fail"

      accounting:
        +schema: "accounting"
      billing:
        +schema: "billing"
      benefit:
        +schema: "benefit"
        +enabled: true
      commission:
        +schema: "commission"
        +enabled: true
      claims:
        +schema: "claims"
        +enabled: true
      membership:
        +schema: "membership"
      policy:
        +schema: "policy"
      provider:
        +schema: "provider"
      reference:
        +schema: "reference"
      dv_raw_vault:
        +schema: "dv_raw_vault"
        +materialized: "incremental"
      dv_staging:
        +schema: "dv_staging"
        +materialized: "view"
        +tags: ["schema: dv_staging","layer: integration"]

    curation:
      +database: "cur_db"
      +materialized: "incremental"
      +incremental_strategy: "merge"
      +on_schema_change: "fail"

      cust_svc:
        +schema: "cust_svc"
        +materialized: "incremental"
        +incremental_strategy: "merge"
        +on_schema_change: "sync_all_columns"
        +persist_docs:
          relation: true
          columns: true

      pcp_attribution:
        +schema: "pcp_attribution"
      reference:
        +schema: "reference"
      edw3:
        +schema: "edw3"
      biz_vault:
        +schema: "biz_vault"

    consumption:
      +database: "con_db"
      +materialized: "incremental"
      +incremental_strategy: "merge"
      +on_schema_change: "fail"

      cust_svc:
        +schema: "cust_svc"
        +materialized: "incremental"
        +incremental_strategy: "merge"
        +on_schema_change: "sync_all_columns"
        +persist_docs:
          relation: true
          columns: true

      extract_elig:
        +schema: "extract_elig"
      extract_claims:
        +schema: "extract_claims"
      reference:
        +schema: "reference"

snapshots:
  edp_data_domain:
    +meta:
      integration:
        +enabled: true
        +target_database: " {%- if env_var('DBT_ENVIRONMENT')|lower == 'team_dev' -%}dev_int_db {%- elif env_var('DBT_ENVIRONMENT')|lower == 'dev' -%} {{ target.database }} {%- else -%} {{ env_var('DBT_ENVIRONMENT') | lower }}_int_db {%- endif -%}"

seeds:
  edp_data_domain:
    +enabled: true
    static:
      +database: "int_db"
      +schema: "static"
    synthetic:
      +database: "int_db"
      +schema: "synthetic"
    reference:
      +database: "int_db"
      +schema: "reference"

tests:
  edp_data_domain:
    +severity: "{% if env_var('DBT_ENVIRONMENT')|lower in ['team_dev','dev','test'] %}warn{%else%}error{% endif %}"
flags:
  require_generic_test_arguments_property: true